"$schema" = "./node_modules/wrangler/config-schema.json"
name = "dapple-preview"
compatibility_date = "2026-05-31"

[assets]
directory = "./packages/preview/dist"
not_found_handling = "single-page-application"

[[routes]]
pattern = "dapple.nore.sh"
zone_id = "4093cac17eb5b21e3dda5ffd039d516e"
